image: docker:19.03.13

stages:
  - lint
  - test
  - build
  - deploy

before_script:
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

lint:
  stage: lint
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker run $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME flake8 --max-line-length=120
    - docker run $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME black --check .
    - docker run $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME black .

test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y docker-compose
    - docker-compose --version
    - docker-compose run web pytest

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .

deploy:
  stage: deploy
  only:
    - master
  script:
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
