image: docker:20.10

stages:
  - build
  - test
  - deploy

variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  EB_APP_NAME: $APP_NAME
  EB_ENV_NAME: $AWS_ELASTIC_BEANSTALK_ENV_NAME
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_PIPELINE_IID

before_script:
  - - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin

build:
  stage: build
  script:
    - docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME .
    - docker push $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - pytest

deploy:
  stage: deploy
  only:
    - main
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install awsebcli
    - eb deploy $EB_ENV_NAME
  environment:
    name: production
  when: manual
