stages:
  - build
  - test
  - deploy

variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  EB_APP_NAME: $APP_NAME
  EB_ENV_NAME: $AWS_ELASTIC_BEANSTALK_ENV_NAME

build:
  stage: build
  image: docker:20.10
  services:
    - docker:20.10-dind
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

test:
  stage: test
  image: docker:20.10
  services:
    - docker:20.10-dind
  script:
    - docker run $CI_REGISTRY_IMAGE pytest

deploy:
  stage: deploy
  image: ubuntu:20.04

  script:
    - apt-get update -qy
    - apt-get install -y python-dev python3-pip
    - pip install awsebcli
    - eb init -p docker $EB_APP_NAME
    - eb create $EB_APP_NAME-env
  environment:
    name: production
