# Generated by Django 3.0 on 2023-12-25 14:12
from django.apps import apps as global_apps
from django.db import migrations


def forwards(apps, schema_editor):
    try:
        OldModel1 = apps.get_model("oc_lettings_site", "Address")
        OldModel2 = apps.get_model("oc_lettings_site", "Letting")
    except LookupError:
        # The old app isn't installed.
        return

    NewModel1 = apps.get_model("lettings", "Address")
    NewModel1.objects.bulk_create(
        NewModel1(number=old_object.number,
                 street=old_object.street,
                 city=old_object.city,
                 state=old_object.state,
                 zip_code=old_object.zip_code,
                 country_iso_code=old_object.country_iso_code)
        for old_object in OldModel1.objects.all()
    )
    NewModel2 = apps.get_model("lettings", "Letting")
    NewModel2.objects.bulk_create(
        NewModel2(title=old_object.title,
                 address=NewModel1.objects.get(id=old_object.address_id))
        for old_object in OldModel2.objects.all()
    )


class Migration(migrations.Migration):
    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
    dependencies = [
        ("oc_lettings_site", "0001_initial"),
        ("lettings", "0001_initial"),
    ]

    if global_apps.is_installed("oc_lettings_site"):
        dependencies.append(("oc_lettings_site", "0001_initial"))



