# Generated by Django 3.0 on 2024-01-02 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0003_auto_20231227_1909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
